### ISSUE TITLE
Maven Dependency

### ISSUE THREAD

**Issue by Serializator** [olivervscreeper/NetworkUtilities#14]
The CraftBukkit dependency isn't working, and in the URL specified in the Bukkit repository I couldn't find a "bukkit" folder in the "org" folder.

http://gyazo.com/7378a23a119e97a19af859f46f14d4a4
http://gyazo.com/b21b3967c6d323af4fd6bc833ecea8ca

**Comment by olivervscreeper** [comment]
Because of the recent DCMA issues, it's against the law to put Bukkit in any repo's - really annoying! You need to run BuildTools.jar from the Spigot site on your PC, and it'll be placed in your Maven repo locally on your PC. Thus, it pulls this from your PC and nowhere else.

**Comment by Serializator** [comment]
If the repository isn't working, why did you add it?

**Comment by olivervscreeper** [comment]
Missunderstood you at first, I've ammended the issue in the latest commit.
