### ISSUE TITLE
Event Duplication

### ISSUE THREAD

**Issue by Serializator** [olivervscreeper/NetworkUtilities#16]
Dear olivervscreeper,

The class isn't unregistered when the PlayerCloseInventory event is getting fired, this will cause duplication. If you open a Menu three times and close it with ESC without clicking a MenuItem it will duplicate three times, if you eventually click the MenuItem it will execute the code you put in the onClick(Player); method three times.

With regards,
Julian v.d Berkmortel

**Comment by olivervscreeper** [comment]
Fixed in your latest merge.
